# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160711_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='contenido',
            new_name='bibliografia',
        ),
    ]
