# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_autor_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
