# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_autor_libros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='libros',
        ),
    ]
