# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_autor_libros'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='creada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
